everblock_admin_configuration:
  path: /everblock/configuration
  methods: [GET, POST]
  defaults:
    _controller: 'Everblock\\Tools\\Controller\\Admin\\EverblockConfigurationController::index'
    _legacy_controller: AdminEverBlockConfiguration
    _legacy_link: AdminEverBlockConfiguration
